### ISSUE TITLE
Attempting to run on mac os, field inventories not found in configuration

### ISSUE THREAD

**Issue by omenking** [aws-samples/aws-auto-inventory#1]
Attempting to run, having a bit of trouble:

<img width="840" alt="Screen Shot 2021-05-03 at 9 08 25 AM" src="https://user-images.githubusercontent.com/7776/116879867-38002880-abef-11eb-943c-c19735b13b00.png">

**Comment by valter-silva-au** [comment]
Hi @omenking, thank you for opening this issue. It seems that the CLI can't find the config file. Make sure the config exists on the right path, you can read more about it [here](https://github.com/aws-samples/aws-auto-inventory#installing). 
For example on Mac:

```
$ mv ~/.config/aws-auto-inventory/config.yaml ~/.config/aws-auto-inventory/config.bkp
$ ./dist/aws-auto-inventory-darwin-x86_64 --name cloudlab
Field inventories not found in configuration
```

**Comment by str3tch** [comment]
I had this same issue. I had created `config.yml` instead of `config.yaml`, looks like you have done the same @omenking
