### ISSUE TITLE
Add option to output information as a CSV file or JSON instead of in a spreadsheet

### ISSUE THREAD

**Issue by keanu-001** [aws-samples/aws-auto-inventory#41]
The company I work for is looking at using this tool to create an inventory of our AWS resources. We would like to have the option to export the information gathered by this tool in a CSV file format or JSON. 

We have considered converting the file after the fact but we believe that others would benefit from this feature too.

Given that the tool uses pandas to write the output file it should be simple to add other file formats. 

I would be happy to take on this task.

**Comment by adenot** [comment]
change the write_data function at app/doc.py to:

```
import json

def write_data(name, inventory, data):
    with open("output/%s.json" % name, "w") as outfile:
        json.dump(data, outfile, indent=4, sort_keys=True, default=str)
```
