### ISSUE TITLE
service output json file should contain both service/function names

### ISSUE THREAD

**Issue by sleonov** [aws-samples/aws-auto-inventory#57]
code in main function storing service results should use both service name and function name to create unique file names, 
since there could be different function names.

- Version: Latest
- Local OS Version: MacOS 13.6.2
- Local chip architecture: Apple M1
- Reproduces in: NA

Steps to Reproduce:

Run scan with config file containing multiple functions of the same service

**Comment by sleonov** [comment]
Will be happy to raise PR

**Comment by valter-silva-au** [comment]
Hi @sleonov , please go ahead and raise the PR :)

**Comment by sleonov** [comment]
PR: https://github.com/aws-samples/aws-auto-inventory/pull/59
