### ISSUE TITLE
Support --no-verify-ssl option (so client handle can be created with verify=False)

### ISSUE THREAD

**Issue by sleonov** [aws-samples/aws-auto-inventory#58]
Type your idea here.

**Comment by sleonov** [comment]
Will be happy to raise PR

**Comment by valter-silva-au** [comment]
`Hi @sleonov could you please expand on the use case? Why would such parameter be useful?

**Comment by sleonov** [comment]
I guess for the same reason aws cli has it - when client is behind
corporate proxy and SSL verification fails.
